### PR TITLE
fix: improve error logging

### LINKED ISSUE #22: SyntaxError: Unexpected token < in JSON at position 0
Sentry Issue: [SUBGRAPHER-1](https://snapshot-labs.sentry.io/issues/4493643081/?referrer=github_integration)

```
SyntaxError: Unexpected token < in JSON at position 0
  File "/workspace/dist/src/utils.js", line 27, in graphqlQuery
    responseData = JSON.parse(responseData);
  File "/workspace/dist/src/api.js", line 65, in getData
    const result = await (0, utils_1.graphqlQuery)(url, query);
```

### PR DESCRIPTION
**Pull request by wa0x6e**
## 🧿 Current issues / What's wrong ?

Currently, when subgraph request is failing due to network error (timeout, etc...), it just log a `JSON.parse` error on Sentry, and return an error with the text response on the caller side.

See error example: https://snapshot-labs.sentry.io/issues/4493643081/?project=4505917750247424&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=30d&stream_index=0

## 💊 Fixes / Solution

Fix #22

Improve logging and error message when subgraph url is returning text message due to network error.

## 🚧 Changes

- When request is failing due to network error, log the network error on Sentry, which will be more useful than logging a `JSON.parse error`, which tell us nothing, since we try/catch a json.parse already.
- On caller side, also return a more meaningful error than an Error with just the request body content
- On user input error, return 400 error code

### CODE REVIEW

**Review by ChaituVR — APPROVED** [review]
utAck

File: src/api.ts [hunk 1]
```diff
@@ -47,10 +47,13 @@ router.post('/*', async (req, res) => {
...
     if (result.errors) {
       capture(new Error('GraphQl error'), result.errors);
-      return res.status(500).json(result);
+      return res.status(400).json(result);
     }
     return res.json(result);
   } catch (error: any) {
+    if (error.errors) {
+      return res.status(500).json(error);
+    }
```
Comment (ChaituVR) [inline src/api.ts]: Fetch error can contain `errors`? 🤔

Comment (wa0x6e) [reply src/api.ts]: This is for errors returned by graphql, like "Skip limit can not be over X", formatted like `{errors: [{message: 'xxx'}]}`

Comment (ChaituVR) [reply src/api.ts]: These go into `catch`? 🤔  i don't think so

Comment (wa0x6e) [reply src/api.ts]: From here https://github.com/snapshot-labs/subgrapher/blob/main/src/api.ts#L48

This function is not used exclusively on try/catch
